# Generated by Django 5.0.1 on 2024-05-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(default="image/profile.png", upload_to="images"),
        ),
    ]
