# Generated by Django 5.0.1 on 2024-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_profile_profile_pic_category_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="thumbnail_image",
            field=models.ImageField(default=2, upload_to="blog/img"),
            preserve_default=False,
        ),
    ]
