# Generated by Django 5.0.1 on 2024-05-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="staff",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Approved", "Approved")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
